### ISSUE TITLE
Is it possible to change the year limits for Rstudio CRAN downloads?

### ISSUE THREAD

**Issue by martinamorris** [GuangchuangYu/dlstats#4]
Hi -- not sure your repo is the best place for this question, but I don't know where else to ask.

The [Rstudio CRAN package downloads](http://cran-logs.rstudio.com/) go back to 2012, but the `cran_stats()` function only retrieves data back to 2017 due to this: https://github.com/GuangchuangYu/dlstats/blob/9d3e09c021418d54f039ddcd384375688910930f/R/cran_stats.R#L86.  

Would you be willing to modify this hardcoded date limit and supply a start year argument to the function?

thanks!

**Comment by GuangchuangYu** [comment]
![image](https://user-images.githubusercontent.com/626539/206639578-fc65be11-07e8-4dc4-885e-e7ea177f5c86.png)

You can use `set_cran_start_year` in `dlstats` v >= 0.1.6

**Comment by martinamorris** [comment]
Thanks!
